### ISSUE TITLE
Winetricks not working

### ISSUE THREAD

**Issue by blackxfiied** [ncruces/zenity#103]
Logs:
```
winetricks                    
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You apppear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
Using winetricks 20240105 - sha256sum: 8f28985b06e9e04b5268e2aef3429b2a0f6abd4fd12c4a30472dfe66355128fa with wine-9.0-rc4 (Staging) and WINEARCH=win64
Running on OSX, but DISPLAY is not set...probably using Mac Driver.
winetricks GUI enabled, using zenity zenity v0.10.12 darwin/amd64
https://github.com/ncruces/zenity
flag provided but not defined: -hide-column
```
EOF

Using macOS 14.4.1, M1 Pro
Using zenity 0.10.12 (latest) and brew (latest) both don't work.

**Comment by ncruces** [comment]
I don't support the `-hide-column` flag, so I guess this issue should be raised with `winetricks`?
I can't support everything `zenity` does, that's beyond scope: see https://github.com/ncruces/zenity/issues/11#issuecomment-1558924195.

If this is a request that I support `-hide-column`, note that the List dialog is very simplified (again, see #11). I will not support anything more complex in terms of UI, because it wouldn't work on macOS: I work with what `osascript` gives me.

If the intent is to show just one column and _hide others_, I'd need to see the use case. So, again, go to `winetricks`, report the bug, and if they come back with a command and a use case, I can see what I can do.

I'll leave this open for a while, waiting on that feedback, but will eventually close if there's nothing to do here.
