### ISSUE TITLE
Collaboration on Swift for Darwin

### ISSUE THREAD

**Issue by gabyx** [ncruces/zenity#21]
Hi Nuno,

 I thought I drop a note here:

I was experimenting recently with the fact that Swift is able to compile an NSAlert message box far better than the shitty AppleScript thing we are both doing in our libs.

I was wondering if we could collaborate on making the dialogs more robust and nicer and more native on macOS. The message box I have already together, the thing would be to run the script with `swift` or just execute the script if its `chmod +x`.

Run the [following script](https://github.com/gabyx/Githooks/blob/feature/wrap-button-options-over-zenity/githooks/apps/dialog/gui/darwin/swift/dialog.swift) with 

```shell
swift dialog.swift message info warning "Title here..." "Message here..." Ok Cancel 3 A B C
```

I have not yet together the NSAlert with `NSViewTable` where we put all options in, that would be awesome. Maybe we could give a try in hacking together a simple script which makes `zenity --list` at least with some basic options, basically extending my script above. What do you think =).
So far I am far more convinced this is a future proof solution (except the fact that apple changes stuff and it won't compile anymore (so far it works on Big Sur and High Sierra (which is a good thing) (probably needs compiler directives etc which is possible in Swift). Furthermore its not shitty ApplyScript which I have a hard time in understanding...

**Comment by ncruces** [comment]
Swift is definitely interesting, but if you look at #11, I'm pretty close to considering this "feature complete".

Additionally, I actually like JXA, and although I (incidentally) use a mac everyday for work, ATM I have very little appetite to learn Swift.  It does annoy me that some dialogs turned out impossible to implement in JXA because of [this](https://github.com/JXA-Cookbook/JXA-Cookbook/issues/53).

The truth is: I don't have an actual need for anything that's missing (mostly, I needed the file dialogs), and no one seems to be interested either. So I'd be embarking on a complete rewrite of the mac support here "just for fun".

That's... a tough sell.

**Comment by gabyx** [comment]
Jeah, I understand. The thing is the dialog just look shitty in macOS, and it does not even really dynamically make the list bigger, when to many entries are added... the JXA thing is so horribly abandoned by Apple, i most likely will replace it. JXA would have been good if there is documentation, but actually there is none which is official enough to be used...

**Comment by ncruces** [comment]
JXA seems to have been [fixed](https://github.com/JXA-Cookbook/JXA-Cookbook/issues/53#issuecomment-975722054), I'll work to add the two missing dialogs, as per #11.
