### ISSUE TITLE
Icon option should specify supported file extension

### ISSUE THREAD

**Issue by princessmortix** [ncruces/zenity#35]
On the documention, I think it should be specified that PNG files are supported (tested on Windows, haven't checked MacOS).

Also, do you plan adding support for .ico files? I thinking it would be useful using .ico instead of .png (Or maybe even use the .ico files present on some Windows DLLs like shell32.dll)

**Comment by ncruces** [comment]
I can try to document the behavior better, but file formats are kinda open-ended.

For `zenity.Icon`:
- on *unix* files aren't supported, only "GTK icon names."
- on *windows* PNGs and ICOs are supposed to be supported
  - the main icon from an EXE file might be interesting
  - more than that is overcomplicating for no reason
  - happy to be proven wrong by working patches
- on *macOS*, for the most part, anything goes:
  - I tried at least ICNSs, PNGs, JPEGs

For `zenity.WindowIcon`:
- on *unix* I think PNGs should be supported, not sure about anything else
- *windows* and *macOS* should be similar to above

So, if you want to be cross platform, just use PNGs.
Otherwise, try it out on your platform..

**Comment by princessmortix** [comment]
All right, thanks for the explaination.

About 
> - more than that is overcomplicating for no reason

I've never played with DLLs using Go, I might will take a look to see if I can submit a patch.

****

> on _windows_ PNGs and ICOs are supposed to be supported

ICOs didn't worked here on Windows, only PNGs files.

**Comment by ncruces** [comment]
ICO files worked for some things, not others, but this should be fixed in master.

**Comment by ncruces** [comment]
> I've never played with DLLs using Go, I might will take a look to see if I can submit a patch.

My problem with icons from DLLs is one of API.

Currently, the API is for both `zenity.Icon` and `zenity.WindowIcon` is: they take a `zenity.DialogIcon` or a `string` and try their best with that.

The `string` can be a file path (PNG works best, most cross platform), or an "icon name" (on Unix; the list of available icon names is reasonably unpredictable).

To specify a resource within an DLL, what would you pass in? The functions take `any`, so you can add other stuff, but what? A `uintptr` handle, and _you_ load the icon?

**Comment by ncruces** [comment]
Using the icon from an EXE file now also works, which might be useful to get the application's own icon.
Welcome to review patches implementing alternatives.

**Comment by princessmortix** [comment]
> To specify a resource within an DLL, what would you pass in? The functions take any, so you can add other stuff, but what? A uintptr handle, and you load the icon?

Something like `zenity.Icon(zenity.DllIcon("file.dll", 5))`

being 5 the icon index

**Comment by ncruces** [comment]
Well, that's something I'd rather not do.

Like, consider what `zenity.DllIcon` would do on macOS:
- if it doesn't exist, it forces you to only use it on files that have a `windows` build tag;
   it also makes it less discoverable in the package documentation;
- if it exists but panics, you need to hide it behind a `if runtime.GOOS == "windows"`;
- if it errors out, or returns a default, it gets harder than that to use, especially on cross platform apps.

This would be the first API of its kind: totally platform specific, and not a simple flag that's easy to ignore on other platforms.

**Comment by princessmortix** [comment]
Understood. Thanks for the attention and your work on this package!
