### ISSUE TITLE
dialog.vtbl.SetDefaultFolder should be dialog.vtbl.SetFolder

### ISSUE THREAD

**Issue by gabyx** [ncruces/zenity#5]
Bug in `file_windows.go` : 

- SetDefaultFolder always uses the "recently used folder" if any is set in the system
- Also the filename (path) needs to be  
- `opts.filename, err = filepath.Abs(filepath.FromSlash(opts.filename))` before `shCreateItemFromParsingName` is called.

**Comment by ncruces** [comment]
Using `SetDefaultFolder` was deliberate. I'm trying to match the behaviour of `OPENFILENAMEW`'s `lpstrInitialDir` on Windows 7 and above. That's also the behaviour Windows *users* would expect in most situations, I guess (though not necessarily *developers*, I personally cringe at those rules).

`IFileDialog` is only used for folders, since for files `GetOpenFileNameW` provides better compatibility (in particular, with Server Core). I'd like to keep it that way if at all possible.

Whatever behaviour is chosen for folders, should match the one for files, IMO, unless it is so utterly broken that it forces me to use `IFileDialog` for everything (with the unavoidable fallbacks).

As for the other issue, why should Go resolve the absolute path? Doesn't Windows?
And if I go there, should I do that on every platform?

**Comment by gabyx** [comment]
Ah, good to know. It is really broken, Windows is a mess. In my tool, I just copy&paste and refactor for githooks. I need correct behavior, if you set the location in my tool with `dialog --root "../.."` windows jokes in the IFileDialog ShellItem stuff... I think it really needs an absolute path. For me it did not work. So I resolved it with that. 

FYI: The code is here: https://github.com/gabyx/githooks/tree/feature/gui-dialog/githooks/apps/dialog

**Comment by ncruces** [comment]
Revisiting this, it really seems broken beyond repair.

I fixed it for folders with `SetFolder` on `IFileDialog` and tried to match it with combination of `OPENFILENAMEW`'s `lpstrFile` & `lpstrInitialDir` elsewhere.

To get perfect consistency, I'd have to use `IFileDialog` everywhere, but that's duplicating everything (since I need `GetOpenFileNameW` for compatibility - and not just backwards compatibility, any Windows without Explorer such as Server Core, needs it).
